name: Trivy Vulnerability Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trivy:
    name: Scan Docker image for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-app:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-app:latest
          format: table
          ignore-unfixed: true
